"""Research presets for Deep Research Agent."""

RESEARCH_PRESETS = {
    "quick": {
        "label": "Quick",
        "description": "Fast overview \u2014 ~3\u20134 sections, ~5 min, ~2k words",
        "overrides": {
            "research.min_initial_tasks": 3,
            "research.max_total_tasks": 10,
            "research.tasks_per_section": 2,
            "research.enable_recursion": False,
            "research.max_recursion_depth": 0,
            "research.max_runtime_hours": 1,
            "research.max_loops": 10,
            "research.max_concurrent_tasks": 2,
            "search.queries_per_task": 3,
            "search.results_per_query": 2,
            "search.pre_plan_queries": 2,
            "search.pre_plan_max_results": 5,
            "search.gap_fill_queries": 0,
            "search.gap_fill_max_results": 0,
            "gap_analysis.enabled": False,
            "synthesis.min_words_per_section": 200,
            "synthesis.max_words_per_section": 600,
            "synthesis.min_citations_per_section": 1,
            "synthesis.style": "confident",
        },
    },
    "standard": {
        "label": "Standard",
        "description": "Balanced research \u2014 ~5\u20137 sections, ~20 min, ~6k words",
        "overrides": {
            "research.min_initial_tasks": 5,
            "research.max_total_tasks": 25,
            "research.tasks_per_section": 3,
            "research.enable_recursion": True,
            "research.max_recursion_depth": 1,
            "research.max_runtime_hours": 2,
            "research.max_loops": 25,
            "research.max_concurrent_tasks": 3,
            "search.queries_per_task": 4,
            "search.results_per_query": 2,
            "search.pre_plan_queries": 4,
            "search.pre_plan_max_results": 8,
            "search.gap_fill_queries": 1,
            "search.gap_fill_max_results": 3,
            "gap_analysis.enabled": True,
            "gap_analysis.max_new_sections": 2,
            "gap_analysis.max_gap_fill_tasks": 6,
            "synthesis.min_words_per_section": 400,
            "synthesis.max_words_per_section": 1500,
            "synthesis.min_citations_per_section": 2,
            "synthesis.style": "balanced",
        },
    },
    "deep": {
        "label": "Deep",
        "description": "Thorough analysis \u2014 ~8\u201312 sections, ~1\u20132 hr, ~20k words",
        "overrides": {
            "research.min_initial_tasks": 8,
            "research.max_total_tasks": 50,
            "research.tasks_per_section": 4,
            "research.enable_recursion": True,
            "research.max_recursion_depth": 2,
            "research.max_runtime_hours": 6,
            "research.max_loops": 50,
            "research.max_concurrent_tasks": 3,
            "search.queries_per_task": 5,
            "search.results_per_query": 2,
            "search.pre_plan_queries": 6,
            "search.pre_plan_max_results": 10,
            "search.gap_fill_queries": 2,
            "search.gap_fill_max_results": 5,
            "gap_analysis.enabled": True,
            "gap_analysis.max_new_sections": 3,
            "gap_analysis.max_gap_fill_tasks": 10,
            "synthesis.min_words_per_section": 800,
            "synthesis.max_words_per_section": 2500,
            "synthesis.min_citations_per_section": 4,
            "synthesis.style": "thorough",
        },
    },
    "exhaustive": {
        "label": "Exhaustive",
        "description": "Comprehensive \u2014 ~12\u201318 sections, ~3\u20136 hr, ~40k+ words",
        "overrides": {
            "research.min_initial_tasks": 12,
            "research.max_total_tasks": 100,
            "research.tasks_per_section": 5,
            "research.enable_recursion": True,
            "research.max_recursion_depth": 3,
            "research.max_runtime_hours": 24,
            "research.max_loops": 100,
            "research.max_concurrent_tasks": 4,
            "search.queries_per_task": 6,
            "search.results_per_query": 2,
            "search.pre_plan_queries": 8,
            "search.pre_plan_max_results": 10,
            "search.gap_fill_queries": 3,
            "search.gap_fill_max_results": 5,
            "gap_analysis.enabled": True,
            "gap_analysis.max_new_sections": 5,
            "gap_analysis.max_gap_fill_tasks": 15,
            "synthesis.min_words_per_section": 1500,
            "synthesis.max_words_per_section": 4000,
            "synthesis.min_citations_per_section": 6,
            "synthesis.style": "thorough",
        },
    },
}
